### ISSUE TITLE
Use your slides...  can I do?

### ISSUE THREAD

**Issue by szaghi** [alexpacheco/fortran#1]
Dear @alexpacheco,

thank you very much for sharing your work, it is very appreciated. 

In the near future it could happen (hopefully for me not...) that I have to _teach_ to a small set of my colleagues some of the new features of modern Fortran standards (2003+). I found your tex sources a great basis for this possible, future (informal) mini-course, thus, can I use some of your slides? 

In the (unfortunate) case I will have to do such lectures I will share my slides too and I will explicitly cite your copyright.

My best regards,
Stefano

**Comment by alexpacheco** [comment]
Sure, not a problem. I've added a Creative Commons License that I thought was included.

Regards
Alex

**Comment by szaghi** [comment]
Many thanks!

**Comment by szaghi** [comment]
@alexpacheco 

Dear Alex,

I start to write my talk, I am using a lot of your contents http://szaghi.github.io/zen-of-fortran-talk/#/slide-0

> Java script must work on your browser to correctly read the Talk.

At the current last slide I cited your work http://szaghi.github.io/zen-of-fortran-talk/#/slide-35

I hope this is ok for you.

Thank you again,

My best regards.

**Comment by alexpacheco** [comment]
Sounds Good
